name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: frontend
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{ vars.AWS_DEPLOY_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install global dependencies
        run: npm install -g aws-cdk
 
      - name: Install dependencies server
        working-directory: frontend/healthcare-portal-server
        run: npm ci
        
      - name: Build portal
        working-directory: frontend/healthcare-portal
        env:
          CI: ""
          BUILD_PATH: ${{ vars.BUILD_PATH }}
        run: |
          npm ci
          npm run build 
          
      - name: Deploy frontend
        working-directory: frontend/healthcare-portal-cdk
        run: |
          npm ci
          cdk deploy --require-approval never
